# *****************************************************************************
#
#   Part of the py5 library
#   Copyright (C) 2020-2024 Jim Schmitz
#
#   This library is free software: you can redistribute it and/or modify it
#   under the terms of the GNU Lesser General Public License as published by
#   the Free Software Foundation, either version 2.1 of the License, or (at
#   your option) any later version.
#
#   This library is distributed in the hope that it will be useful, but
#   WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
#   General Public License for more details.
#
#   You should have received a copy of the GNU Lesser General Public License
#   along with this library. If not, see <https://www.gnu.org/licenses/>.
#
# *****************************************************************************


MAGMA = "magma"
INFERNO = "inferno"
PLASMA = "plasma"
VIRIDIS = "viridis"
CIVIDIS = "cividis"
TWILIGHT = "twilight"
TWILIGHT_SHIFTED = "twilight_shifted"
TURBO = "turbo"
BLUES = "Blues"
BRBG = "BrBG"
BUGN = "BuGn"
BUPU = "BuPu"
CMRMAP = "CMRmap"
GNBU = "GnBu"
GREENS = "Greens"
GREYS = "Greys"
ORRD = "OrRd"
ORANGES = "Oranges"
PRGN = "PRGn"
PIYG = "PiYG"
PUBU = "PuBu"
PUBUGN = "PuBuGn"
PUOR = "PuOr"
PURD = "PuRd"
PURPLES = "Purples"
RDBU = "RdBu"
RDGY = "RdGy"
RDPU = "RdPu"
RDYLBU = "RdYlBu"
RDYLGN = "RdYlGn"
REDS = "Reds"
SPECTRAL = "Spectral"
WISTIA = "Wistia"
YLGN = "YlGn"
YLGNBU = "YlGnBu"
YLORBR = "YlOrBr"
YLORRD = "YlOrRd"
AFMHOT = "afmhot"
AUTUMN = "autumn"
BINARY = "binary"
BONE = "bone"
BRG = "brg"
BWR = "bwr"
COOL = "cool"
COOLWARM = "coolwarm"
COPPER = "copper"
CUBEHELIX = "cubehelix"
FLAG = "flag"
GIST_EARTH = "gist_earth"
GIST_GRAY = "gist_gray"
GIST_HEAT = "gist_heat"
GIST_NCAR = "gist_ncar"
GIST_RAINBOW = "gist_rainbow"
GIST_STERN = "gist_stern"
GIST_YARG = "gist_yarg"
GNUPLOT = "gnuplot"
GNUPLOT2 = "gnuplot2"
GRAY = "gray"
HOT = "hot"
HSV = "hsv"
JET = "jet"
NIPY_SPECTRAL = "nipy_spectral"
OCEAN = "ocean"
PINK = "pink"
PRISM = "prism"
RAINBOW = "rainbow"
SEISMIC = "seismic"
SPRING = "spring"
SUMMER = "summer"
TERRAIN = "terrain"
WINTER = "winter"
ACCENT = "Accent"
DARK2 = "Dark2"
PAIRED = "Paired"
PASTEL1 = "Pastel1"
PASTEL2 = "Pastel2"
SET1 = "Set1"
SET2 = "Set2"
SET3 = "Set3"
TAB10 = "tab10"
TAB20 = "tab20"
TAB20B = "tab20b"
TAB20C = "tab20c"
GREY = "grey"
GIST_GREY = "gist_grey"
GIST_YERG = "gist_yerg"
GRAYS = "Grays"
MAGMA_R = "magma_r"
INFERNO_R = "inferno_r"
PLASMA_R = "plasma_r"
VIRIDIS_R = "viridis_r"
CIVIDIS_R = "cividis_r"
TWILIGHT_R = "twilight_r"
TWILIGHT_SHIFTED_R = "twilight_shifted_r"
TURBO_R = "turbo_r"
BLUES_R = "Blues_r"
BRBG_R = "BrBG_r"
BUGN_R = "BuGn_r"
BUPU_R = "BuPu_r"
CMRMAP_R = "CMRmap_r"
GNBU_R = "GnBu_r"
GREENS_R = "Greens_r"
GREYS_R = "Greys_r"
ORRD_R = "OrRd_r"
ORANGES_R = "Oranges_r"
PRGN_R = "PRGn_r"
PIYG_R = "PiYG_r"
PUBU_R = "PuBu_r"
PUBUGN_R = "PuBuGn_r"
PUOR_R = "PuOr_r"
PURD_R = "PuRd_r"
PURPLES_R = "Purples_r"
RDBU_R = "RdBu_r"
RDGY_R = "RdGy_r"
RDPU_R = "RdPu_r"
RDYLBU_R = "RdYlBu_r"
RDYLGN_R = "RdYlGn_r"
REDS_R = "Reds_r"
SPECTRAL_R = "Spectral_r"
WISTIA_R = "Wistia_r"
YLGN_R = "YlGn_r"
YLGNBU_R = "YlGnBu_r"
YLORBR_R = "YlOrBr_r"
YLORRD_R = "YlOrRd_r"
AFMHOT_R = "afmhot_r"
AUTUMN_R = "autumn_r"
BINARY_R = "binary_r"
BONE_R = "bone_r"
BRG_R = "brg_r"
BWR_R = "bwr_r"
COOL_R = "cool_r"
COOLWARM_R = "coolwarm_r"
COPPER_R = "copper_r"
CUBEHELIX_R = "cubehelix_r"
FLAG_R = "flag_r"
GIST_EARTH_R = "gist_earth_r"
GIST_GRAY_R = "gist_gray_r"
GIST_HEAT_R = "gist_heat_r"
GIST_NCAR_R = "gist_ncar_r"
GIST_RAINBOW_R = "gist_rainbow_r"
GIST_STERN_R = "gist_stern_r"
GIST_YARG_R = "gist_yarg_r"
GNUPLOT_R = "gnuplot_r"
GNUPLOT2_R = "gnuplot2_r"
GRAY_R = "gray_r"
HOT_R = "hot_r"
HSV_R = "hsv_r"
JET_R = "jet_r"
NIPY_SPECTRAL_R = "nipy_spectral_r"
OCEAN_R = "ocean_r"
PINK_R = "pink_r"
PRISM_R = "prism_r"
RAINBOW_R = "rainbow_r"
SEISMIC_R = "seismic_r"
SPRING_R = "spring_r"
SUMMER_R = "summer_r"
TERRAIN_R = "terrain_r"
WINTER_R = "winter_r"
ACCENT_R = "Accent_r"
DARK2_R = "Dark2_r"
PAIRED_R = "Paired_r"
PASTEL1_R = "Pastel1_r"
PASTEL2_R = "Pastel2_r"
SET1_R = "Set1_r"
SET2_R = "Set2_r"
SET3_R = "Set3_r"
TAB10_R = "tab10_r"
TAB20_R = "tab20_r"
TAB20B_R = "tab20b_r"
TAB20C_R = "tab20c_r"
